### ISSUE TITLE
Quelea Stage Mode can not connect to the remote server

### ISSUE THREAD

**Issue by irnjunior** [quelea-projection/quelea-android-remote#1]
Quelea Stage Mode can not connect to the remote server, even by configuring it manually. Other applications (Mobile Remote and Mobile Lyrics) work normally.

Since Git was not created for him, I'm commenting here.

God bless them!

**Comment by ArvidNy** [comment]
Thanks for the bug report! This should now be resolved and you should be able to download a new version from the Play Store within a couple of hours. Let me know if it worked for you.

**Comment by irnjunior** [comment]
This worked perfectly.

Thanks for the speed and cordiality.

God bless them!

**Comment by ArvidNy** [comment]
Great, thanks for letting me know!
